import { notFound } from "next/navigation";
import { Icon } from "@/components/icon";
import { faStatus } from "@/components/fa";
import { NutritionLogForm, StartNutritionLog } from "@/components/user/nutrition-execution";
import { requireCurrentUser } from "@/lib/session";
import { prisma } from "@/lib/prisma";

type PageProps = { searchParams: Promise<{ log?: string }> };
export default async function UserNutritionPage({ searchParams }: PageProps) {
  const user = await requireCurrentUser(["USER"]); const { log: logId } = await searchParams;
  if (logId) {
    const log = await prisma.nutritionLog.findFirst({ where: { id: logId, userId: user.id }, select: { id: true, dietDay: { select: { name: true, plan: { select: { title: true } } } }, mealLogs: { orderBy: { meal: { order: "asc" } }, select: { mealId: true, completed: true, actualPortion: true, substitution: true, meal: { select: { name: true, scheduledTime: true, foodItems: { orderBy: { order: "asc" }, select: { name: true } } } } } } } });
    if (!log) notFound();
    return <div className="member-page"><NutritionLogForm logId={log.id} title={`${log.dietDay.plan.title} · ${log.dietDay.name}`} initial={log.mealLogs.map((item: any) => ({ mealId: item.mealId, name: item.meal.name, scheduledTime: item.meal.scheduledTime, completed: item.completed, actualPortion: item.actualPortion || "", substitution: item.substitution || "", foods: item.meal.foodItems.map((food: any) => food.name) }))} /></div>;
  }
  const [assignment, recent] = await Promise.all([
    prisma.dietAssignment.findFirst({ where: { userId: user.id, status: "ACTIVE" }, select: { id: true, plan: { select: { title: true, version: true, description: true, dailyCalories: true, dietaryRestrictions: true, trainer: { select: { user: { select: { name: true } } } }, days: { orderBy: { dayNumber: "asc" }, select: { id: true, dayNumber: true, name: true, targetCalories: true, targetProtein: true, targetCarbs: true, targetFat: true, meals: { select: { id: true, name: true, scheduledTime: true, foodItems: { select: { name: true } } } } } } } } }, orderBy: { assignedAt: "desc" } }),
    prisma.nutritionLog.findMany({ where: { userId: user.id }, select: { id: true, logDate: true, completedAt: true, hungerRating: true, energyRating: true, dietDay: { select: { name: true, plan: { select: { title: true } } } }, mealLogs: { select: { completed: true } } }, orderBy: { logDate: "desc" }, take: 10 }),
  ]);
  return <div className="member-page"><header className="member-page__heading"><div><span>تغذیه</span><h1>تغذیه روزانه شما</h1><p>وعده‌ها را ساده نگه دارید، تداوم را ثبت کنید و شرایط‌تان را با مربی در میان بگذارید.</p></div></header>{assignment ? <><section className="member-plan-hero member-plan-hero--nutrition"><span><Icon name="heart" size={25} /></span><div><small>طرح فعال · نسخه {assignment.plan.version}</small><h2>{assignment.plan.title}</h2><p>مربی {assignment.plan.trainer.user.name}{assignment.plan.dietaryRestrictions ? ` · ${assignment.plan.dietaryRestrictions}` : ""}</p></div><div><strong>{assignment.plan.dailyCalories || "—"}</strong><span>هدف کالری</span></div></section><div className="member-nutrition-grid">{assignment.plan.days.map((day: any) => <article key={day.id}><header><span>{day.dayNumber}</span><div><h2>{day.name}</h2><p>{day.targetCalories || assignment.plan.dailyCalories || "منعطف"} kcal · P {day.targetProtein || "—"} / C {day.targetCarbs || "—"} / F {day.targetFat || "—"}</p></div></header><div>{day.meals.map((meal: any) => <section key={meal.id}><span>{meal.scheduledTime || "هر زمان"}</span><div><strong>{meal.name}</strong><small>{meal.foodItems.map((food: any) => food.name).join(", ")}</small></div></section>)}</div><StartNutritionLog assignmentId={assignment.id} dayId={day.id} /></article>)}</div></> : <div className="member-panel member-empty"><Icon name="heart" size={27} /><h2>برنامه تغذیه فعالی وجود ندارد</h2><p>مربی شما هنوز برنامه تغذیه تخصیص نداده است.</p></div>}<section className="member-panel member-history"><div className="member-panel__heading"><div><h2>سوابق تغذیه</h2><p>پایبندی روزانه اخیر</p></div></div>{recent.length ? <div>{recent.map((item: any) => { const complete = item.mealLogs.filter((meal: any) => meal.completed).length; return <article key={item.id}><span className={`member-status ${item.completedAt ? "member-status--completed" : "member-status--in_progress"}`}>{faStatus(item.completedAt ? "COMPLETED" : "IN_PROGRESS")}</span><div><strong>{item.dietDay.name}</strong><small>{item.dietDay.plan.title} · {item.logDate.toLocaleDateString("fa-IR")}</small></div><b>{complete}/{item.mealLogs.length} وعده</b><small>انرژی {item.energyRating || "—"} از ۱۰</small></article>; })}</div> : <p className="member-empty-line">ثبت‌های تغذیه شما اینجا نمایش داده می‌شوند.</p>}</section></div>;
}
