"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/icon";

export function StartNutritionLog({ assignmentId, dayId }: { assignmentId: string; dayId: string }) {
  const [pending, setPending] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  async function start() { setPending(true); setError(""); try { const response = await fetch("/api/user/nutrition-logs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assignmentId, dayId, logDate: new Date().toISOString() }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "ثبت روزانه باز نشد."); return; } router.push(`/user/nutrition?log=${data.log.id}`); router.refresh(); } finally { setPending(false); } }
  return <div className="member-start-action"><button className="member-primary-button" disabled={pending} onClick={start}>{pending ? "در حال باز شدن…" : "ثبت این روز"} <Icon name="arrow" size={14} /></button>{error && <small>{error}</small>}</div>;
}

type Meal = { mealId: string; name: string; scheduledTime: string | null; completed: boolean; actualPortion: string; substitution: string; foods: string[] };
export function NutritionLogForm({ initial, logId, title }: { initial: Meal[]; logId: string; title: string }) {
  const [meals, setMeals] = useState(initial); const [hunger, setHunger] = useState<number | null>(null); const [energy, setEnergy] = useState<number | null>(null); const [notes, setNotes] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  function patch(index: number, values: Partial<Meal>) { setMeals((items) => items.map((item, i) => i === index ? { ...item, ...values } : item)); }
  async function save(completed: boolean) { setPending(true); setError(""); try { const response = await fetch(`/api/user/nutrition-logs/${logId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ completed, hungerRating: hunger, energyRating: energy, notes, meals: meals.map((meal) => ({ mealId: meal.mealId, completed: meal.completed, actualPortion: meal.actualPortion, substitution: meal.substitution })) }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "ثبت تغذیه ذخیره نشد."); return; } router.push("/user/nutrition"); router.refresh(); } finally { setPending(false); } }
  return <section className="member-log-editor"><header><div><span>ثبت روزانه تغذیه</span><h1>{title}</h1><p>وعده‌ها را تیک بزنید و جایگزینی‌ها را ثبت کنید.</p></div><button className="member-secondary-button" onClick={() => router.push("/user/nutrition")}>خروج</button></header><div className="member-meal-log">{meals.map((meal, index) => <article className={meal.completed ? "is-done" : ""} key={meal.mealId}><label><input checked={meal.completed} type="checkbox" onChange={(event) => patch(index, { completed: event.target.checked })} /><span><Icon name="check" size={14} /></span></label><div><strong>{meal.name}</strong><small>{meal.scheduledTime || "زمان منعطف"} · {meal.foods.join(", ")}</small></div><input value={meal.actualPortion} onChange={(event) => patch(index, { actualPortion: event.target.value })} placeholder="مقدار واقعی" /><input value={meal.substitution} onChange={(event) => patch(index, { substitution: event.target.value })} placeholder="جایگزینی" /></article>)}</div><div className="member-log-summary member-log-summary--ratings"><label><span>گرسنگی (۱ تا ۱۰)</span><input min="1" max="10" type="number" value={hunger ?? ""} onChange={(event) => setHunger(event.target.value ? Number(event.target.value) : null)} /></label><label><span>انرژی (۱ تا ۱۰)</span><input min="1" max="10" type="number" value={energy ?? ""} onChange={(event) => setEnergy(event.target.value ? Number(event.target.value) : null)} /></label><label><span>یادداشت روزانه</span><textarea rows={3} value={notes} onChange={(event) => setNotes(event.target.value)} /></label></div>{error && <p className="member-form-error">{error}</p>}<footer><button className="member-secondary-button" disabled={pending} onClick={() => save(false)}>ذخیره برای بعداً</button><button className="member-primary-button" disabled={pending} onClick={() => save(true)}>{pending ? "در حال ذخیره…" : "تکمیل روز"}</button></footer></section>;
}
