"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/icon";

export function MeasurementForm() {
  const [open, setOpen] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/user/measurements", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Unable to save measurement."); return; } const imageUrl = String(form.get("imageUrl") || ""); if (imageUrl) await fetch("/api/user/progress-photos", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ imageUrl, measurementId: data.measurement.id, pose: form.get("pose") }) }); setOpen(false); router.refresh(); } catch { setError("Unable to connect."); } finally { setPending(false); } }
  if (!open) return <button className="member-primary-button" onClick={() => setOpen(true)}><Icon name="plus" size={15} /> Add measurement</button>;
  return <form className="member-measurement-form" onSubmit={submit}><div className="member-form-heading"><div><strong>New progress check-in</strong><span>Add any measurements you track consistently.</span></div><button onClick={() => setOpen(false)} type="button">×</button></div>{error && <p className="member-form-error">{error}</p>}<div><label><span>Date</span><input defaultValue={new Date().toISOString().slice(0,10)} name="recordedAt" type="date" /></label><label><span>Weight (kg)</span><input name="weightKg" step="0.1" type="number" /></label><label><span>Body fat (%)</span><input name="bodyFatPercent" step="0.1" type="number" /></label><label><span>Waist (cm)</span><input name="waistCm" step="0.1" type="number" /></label><label><span>Chest (cm)</span><input name="chestCm" step="0.1" type="number" /></label><label><span>Arm (cm)</span><input name="armCm" step="0.1" type="number" /></label><label><span>Hips (cm)</span><input name="hipsCm" step="0.1" type="number" /></label><label><span>Thigh (cm)</span><input name="thighCm" step="0.1" type="number" /></label><label className="member-form-wide"><span>Notes</span><input name="notes" /></label><label className="member-form-wide"><span>Progress photo URL (optional)</span><input name="imageUrl" placeholder="https://…" type="url" /></label><label><span>Photo pose</span><select name="pose"><option value="Front">Front</option><option value="Side">Side</option><option value="Back">Back</option></select></label></div><footer><button className="member-secondary-button" onClick={() => setOpen(false)} type="button">Cancel</button><button className="member-primary-button" disabled={pending}>{pending ? "Saving…" : "Save check-in"}</button></footer></form>;
}

export function FeedbackReply({ feedbackId }: { feedbackId: string }) {
  const [open, setOpen] = useState(false); const [content, setContent] = useState(""); const [pending, setPending] = useState(false); const router = useRouter();
  async function send() { setPending(true); try { const response = await fetch(`/api/user/feedback/${feedbackId}/reply`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content }) }); if (response.ok) { setOpen(false); setContent(""); router.refresh(); } } finally { setPending(false); } }
  if (!open) return <button className="member-reply-button" onClick={() => setOpen(true)}>Reply</button>;
  return <div className="member-reply-form"><textarea autoFocus value={content} onChange={(event) => setContent(event.target.value)} placeholder="Reply to your trainer…" /><button disabled={pending || content.trim().length < 2} onClick={send}>{pending ? "Sending…" : "Send"}</button><button onClick={() => setOpen(false)}>Cancel</button></div>;
}

export function MarkNotificationsRead() { const [pending, setPending] = useState(false); const router = useRouter(); async function mark() { setPending(true); try { await fetch("/api/user/notifications", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ all: true }) }); router.refresh(); } finally { setPending(false); } } return <button className="member-secondary-button" disabled={pending} onClick={mark}>{pending ? "Updating…" : "Mark all read"}</button>; }
