"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/icon";

export function StartWorkout({ assignmentId, dayId }: { assignmentId: string; dayId: string }) {
  const [pending, setPending] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  async function start() { setPending(true); setError(""); try { const response = await fetch("/api/user/workout-logs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assignmentId, dayId }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Unable to start workout."); return; } router.push(`/user/workouts?log=${data.log.id}`); router.refresh(); } catch { setError("Unable to connect."); } finally { setPending(false); } }
  return <div className="member-start-action"><button className="member-primary-button" disabled={pending} onClick={start}>{pending ? "Starting…" : "Start workout"} <Icon name="arrow" size={14} /></button>{error && <small>{error}</small>}</div>;
}

type Exercise = { exerciseId: string; name: string; prescribedSets: number | null; prescribedReps: string | null; prescribedWeight: string | null; completed: boolean; actualSets: number | null; actualReps: string; actualWeight: string; rpe: number | null; notes: string };
export function WorkoutLogForm({ logId, initial, title }: { logId: string; initial: Exercise[]; title: string }) {
  const [exercises, setExercises] = useState(initial); const [effort, setEffort] = useState<number | null>(null); const [notes, setNotes] = useState(""); const [pending, setPending] = useState(""); const [error, setError] = useState(""); const router = useRouter();
  function patch(index: number, values: Partial<Exercise>) { setExercises((items) => items.map((item, i) => i === index ? { ...item, ...values } : item)); }
  async function save(status: "IN_PROGRESS" | "COMPLETED" | "SKIPPED") { setPending(status); setError(""); try { const response = await fetch(`/api/user/workout-logs/${logId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, perceivedEffort: effort, notes, exercises: exercises.map((item) => ({ exerciseId: item.exerciseId, completed: item.completed, actualSets: item.actualSets, actualReps: item.actualReps, actualWeight: item.actualWeight, rpe: item.rpe, notes: item.notes })) }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Unable to save workout."); return; } router.push("/user/workouts"); router.refresh(); } catch { setError("Unable to connect."); } finally { setPending(""); } }
  return <section className="member-log-editor"><header><div><span>WORKOUT IN PROGRESS</span><h1>{title}</h1><p>Record what you completed and how each exercise felt.</p></div><button className="member-secondary-button" onClick={() => router.push("/user/workouts")}>Exit</button></header><div className="member-exercise-log"><div className="member-exercise-log__head"><span>Done</span><span>Exercise</span><span>Sets</span><span>Reps</span><span>Weight</span><span>RPE</span></div>{exercises.map((exercise, index) => <article className={exercise.completed ? "is-done" : ""} key={exercise.exerciseId}><label><input checked={exercise.completed} type="checkbox" onChange={(event) => patch(index, { completed: event.target.checked })} /><span><Icon name="check" size={13} /></span></label><div><strong>{exercise.name}</strong><small>{exercise.prescribedSets || "—"} sets · {exercise.prescribedReps || "—"} reps · {exercise.prescribedWeight || "bodyweight"}</small></div><input min="0" type="number" value={exercise.actualSets ?? ""} onChange={(event) => patch(index, { actualSets: event.target.value ? Number(event.target.value) : null })} /><input value={exercise.actualReps} onChange={(event) => patch(index, { actualReps: event.target.value })} /><input value={exercise.actualWeight} onChange={(event) => patch(index, { actualWeight: event.target.value })} /><input min="1" max="10" type="number" value={exercise.rpe ?? ""} onChange={(event) => patch(index, { rpe: event.target.value ? Number(event.target.value) : null })} /></article>)}</div><div className="member-log-summary"><label><span>Overall effort (1–10)</span><input min="1" max="10" type="number" value={effort ?? ""} onChange={(event) => setEffort(event.target.value ? Number(event.target.value) : null)} /></label><label><span>Workout notes</span><textarea rows={3} value={notes} onChange={(event) => setNotes(event.target.value)} /></label></div>{error && <p className="member-form-error">{error}</p>}<footer><button className="member-secondary-button" disabled={Boolean(pending)} onClick={() => save("IN_PROGRESS")}>Save for later</button><button className="member-primary-button" disabled={Boolean(pending)} onClick={() => save("COMPLETED")}>{pending === "COMPLETED" ? "Completing…" : "Complete workout"}</button></footer></section>;
}
