import { CreatePlan, PlanCardActions } from "@/components/trainer/plan-list-controls";
import { Icon } from "@/components/icon";
import { requireTrainerAccess } from "@/lib/trainer-access";
import { prisma } from "@/lib/prisma";
import { faStatus } from "@/components/fa";

export default async function WorkoutPlansPage() {
  const access = await requireTrainerAccess();
  const [plans, gyms] = await Promise.all([
    prisma.workoutPlan.findMany({ where: { trainerId: access.profile.id }, select: { id: true, title: true, description: true, status: true, version: true, isTemplate: true, updatedAt: true, gym: { select: { name: true } }, days: { select: { _count: { select: { exercises: true } } } }, _count: { select: { assignments: true, derivedPlans: true } } }, orderBy: [{ status: "asc" }, { updatedAt: "desc" }] }),
    prisma.gymTrainer.findMany({ where: { trainerId: access.profile.id, status: "ACTIVE" }, select: { gym: { select: { id: true, name: true } } }, orderBy: { gym: { name: "asc" } } }),
  ]);
  const active = plans.filter((plan: any) => plan.status === "ACTIVE").length; const drafts = plans.filter((plan: any) => plan.status === "DRAFT").length;
  return <div className="trainer-page"><header className="trainer-page__heading trainer-page__heading--compact"><div><span>طراحی برنامه</span><h1>برنامه‌های تمرین</h1><p>برنامه‌های ساخت‌یافته و نسخه‌دار بسازید و بدون دست‌کاری سوابق، تخصیص دهید.</p></div><CreatePlan gyms={gyms.map((item: any) => item.gym)} kind="workouts" /></header><section className="trainer-summary"><div><span>طرح‌های فعال</span><strong>{active}</strong></div><div><span>پیش‌نویس‌ها</span><strong>{drafts}</strong></div><div><span>تکالیف</span><strong>{plans.reduce((sum: any, plan: any) => sum + plan._count.assignments, 0)}</strong></div><div><span>قالب‌ها</span><strong>{plans.filter((plan: any) => plan.isTemplate).length}</strong></div></section>{plans.length ? <div className="trainer-plan-grid">{plans.map((plan: any) => { const exercises = plan.days.reduce((sum: any, day: any) => sum + day._count.exercises, 0); return <article key={plan.id}><div className="trainer-plan-card__top"><span><Icon name="dumbbell" size={21} /></span><b className={`trainer-status trainer-status--${plan.status.toLowerCase()}`}>{faStatus(plan.status)}</b></div><small>{plan.isTemplate ? "TEMPLATE" : plan.gym?.name || "INDEPENDENT"} · VERSION {plan.version}</small><h2>{plan.title}</h2><p>{plan.description || "توضیحی ثبت نشده است."}</p><div className="trainer-plan-stats"><span><strong>{plan.days.length}</strong><small>روز</small></span><span><strong>{exercises}</strong><small>حرکت‌ها</small></span><span><strong>{plan._count.assignments}</strong><small>تکالیف</small></span></div><PlanCardActions id={plan.id} kind="workouts" status={plan.status} /></article>; })}</div> : <div className="trainer-panel trainer-empty"><Icon name="clipboard" size={26} /><strong>هنوز برنامه تمرینی ساخته نشده است</strong><span>یک قالب آماده یا برنامه ویژه یک شاگرد بسازید.</span></div>}</div>;
}
