import type { CSSProperties } from "react";
import Link from "next/link";
import { Icon } from "@/components/icon";
import { requireTrainerAccess } from "@/lib/trainer-access";
import { prisma } from "@/lib/prisma";
import { faStatus } from "@/components/fa";

export default async function TrainerProgressPage() {
  const access = await requireTrainerAccess(); const since = new Date(); since.setDate(since.getDate() - 30);
  const clients = await prisma.trainerClient.findMany({ where: { trainerId: access.profile.id, status: { in: ["ACTIVE", "PAUSED"] } }, select: { id: true, status: true, user: { select: { name: true, email: true, bodyMeasurements: { select: { weightKg: true, recordedAt: true }, orderBy: { recordedAt: "desc" }, take: 1 } } }, workoutAssignments: { where: { status: "ACTIVE" }, select: { plan: { select: { title: true } }, logs: { where: { startedAt: { gte: since } }, select: { status: true, exerciseLogs: { select: { completed: true } } } } }, take: 1 }, dietAssignments: { where: { status: "ACTIVE" }, select: { plan: { select: { title: true } }, logs: { where: { logDate: { gte: since } }, select: { completedAt: true, mealLogs: { select: { completed: true } } } } }, take: 1 }, feedback: { where: { parentId: null }, select: { id: true }, take: 100 } }, orderBy: { user: { name: "asc" } } });
  return <div className="trainer-page"><header className="trainer-page__heading trainer-page__heading--compact"><div><span>نتایج مراجعان</span><h1>دنبال‌کردن پیشرفت</h1><p>اجرا، روند بدن و گفت‌وگوهای مربی‌گری را دنبال کنید.</p></div></header><div className="trainer-progress-grid">{clients.map((client: any) => { const workoutLogs = client.workoutAssignments[0]?.logs || []; const exercises = workoutLogs.flatMap((log: any) => log.exerciseLogs); const workoutRate = exercises.length ? Math.round(exercises.filter((item: any) => item.completed).length / exercises.length * 100) : 0; const nutritionLogs = client.dietAssignments[0]?.logs || []; const meals = nutritionLogs.flatMap((log: any) => log.mealLogs); const nutritionRate = meals.length ? Math.round(meals.filter((item: any) => item.completed).length / meals.length * 100) : 0; const latest = client.user.bodyMeasurements[0]; return <Link href={`/trainer/progress/${client.id}`} key={client.id}><div className="trainer-progress-card__top"><span className="trainer-avatar">{client.user.name.slice(0,2).toUpperCase()}</span><b className={`trainer-status trainer-status--${client.status.toLowerCase()}`}>{faStatus(client.status)}</b></div><h2>{client.user.name}</h2><p>{client.user.email}</p><div className="trainer-progress-rings"><span style={{ "--value": `${workoutRate}%` } as CSSProperties}><i>{workoutRate}%</i><small>تمرین‌ها</small></span><span style={{ "--value": `${nutritionRate}%` } as CSSProperties}><i>{nutritionRate}%</i><small>تغذیه</small></span></div><div className="trainer-progress-card__meta"><span><Icon name="trend" size={14} /> {latest?.weightKg ? `${latest.weightKg} کیلوگرم` : "اندازه‌گیری ثبت نشده"}</span><span>{client.feedback.length} رشته‌های بازخورد</span></div><footer>مشاهده پیشرفت <Icon name="arrow" size={14} /></footer></Link>; })}</div>{!clients.length && <div className="trainer-panel trainer-empty"><Icon name="trend" size={26} /><strong>مراجع فعالی وجود ندارد</strong><span>پیشرفت مراجع اینجا نمایش داده می‌شود.</span></div>}</div>;
}
