import { CreatePlan, PlanCardActions } from "@/components/trainer/plan-list-controls";
import { Icon } from "@/components/icon";
import { requireTrainerAccess } from "@/lib/trainer-access";
import { prisma } from "@/lib/prisma";
import { faStatus } from "@/components/fa";

export default async function NutritionPlansPage() {
  const access = await requireTrainerAccess();
  const [plans, gyms] = await Promise.all([
    prisma.dietPlan.findMany({ where: { trainerId: access.profile.id }, select: { id: true, title: true, description: true, dailyCalories: true, status: true, version: true, isTemplate: true, updatedAt: true, gym: { select: { name: true } }, days: { select: { meals: { select: { _count: { select: { foodItems: true } } } } } }, _count: { select: { assignments: true } } }, orderBy: [{ status: "asc" }, { updatedAt: "desc" }] }),
    prisma.gymTrainer.findMany({ where: { trainerId: access.profile.id, status: "ACTIVE" }, select: { gym: { select: { id: true, name: true } } }, orderBy: { gym: { name: "asc" } } }),
  ]);
  return <div className="trainer-page"><header className="trainer-page__heading trainer-page__heading--compact"><div><span>مربی‌گری تغذیه</span><h1>برنامه‌های تغذیه</h1><p>وعده‌ها، مقدارها، کالری و درشت‌مغذی‌ها را در نسخه‌های ثابت طرح بچینید.</p></div><CreatePlan gyms={gyms.map((item: any) => item.gym)} kind="nutrition" /></header><section className="trainer-summary"><div><span>طرح‌های فعال</span><strong>{plans.filter((plan: any) => plan.status === "ACTIVE").length}</strong></div><div><span>پیش‌نویس‌ها</span><strong>{plans.filter((plan: any) => plan.status === "DRAFT").length}</strong></div><div><span>تکالیف</span><strong>{plans.reduce((sum: any, plan: any) => sum + plan._count.assignments, 0)}</strong></div><div><span>قالب‌ها</span><strong>{plans.filter((plan: any) => plan.isTemplate).length}</strong></div></section>{plans.length ? <div className="trainer-plan-grid trainer-plan-grid--nutrition">{plans.map((plan: any) => { const meals = plan.days.reduce((sum: any, day: any) => sum + day.meals.length, 0); const foods = plan.days.reduce((sum: any, day: any) => sum + day.meals.reduce((foodSum: any, meal: any) => foodSum + meal._count.foodItems, 0), 0); return <article key={plan.id}><div className="trainer-plan-card__top"><span><Icon name="heart" size={21} /></span><b className={`trainer-status trainer-status--${plan.status.toLowerCase()}`}>{faStatus(plan.status)}</b></div><small>{plan.isTemplate ? "TEMPLATE" : plan.gym?.name || "INDEPENDENT"} · VERSION {plan.version}</small><h2>{plan.title}</h2><p>{plan.description || "توضیحی ثبت نشده است."}</p><div className="trainer-plan-kcal">{plan.dailyCalories ? <><strong>{plan.dailyCalories.toLocaleString("fa-IR")}</strong><span>کیلوکالری / روز</span></> : <span>هدف کالری منعطف</span>}</div><div className="trainer-plan-stats"><span><strong>{plan.days.length}</strong><small>روز</small></span><span><strong>{meals}</strong><small>وعده‌ها</small></span><span><strong>{foods}</strong><small>مواد غذایی</small></span></div><PlanCardActions id={plan.id} kind="nutrition" status={plan.status} /></article>; })}</div> : <div className="trainer-panel trainer-empty"><Icon name="heart" size={26} /><strong>هنوز برنامه تغذیه‌ای ساخته نشده است</strong><span>یک چارچوب وعده یا قالب تغذیه آماده بسازید.</span></div>}</div>;
}
