import { CreatePlan, PlanCardActions } from "@/components/trainer/plan-list-controls";
import { Icon } from "@/components/icon";
import { requireTrainerAccess } from "@/lib/trainer-access";
import { prisma } from "@/lib/prisma";

export default async function NutritionPlansPage() {
  const access = await requireTrainerAccess();
  const [plans, gyms] = await Promise.all([
    prisma.dietPlan.findMany({ where: { trainerId: access.profile.id }, select: { id: true, title: true, description: true, dailyCalories: true, status: true, version: true, isTemplate: true, updatedAt: true, gym: { select: { name: true } }, days: { select: { meals: { select: { _count: { select: { foodItems: true } } } } } }, _count: { select: { assignments: true } } }, orderBy: [{ status: "asc" }, { updatedAt: "desc" }] }),
    prisma.gymTrainer.findMany({ where: { trainerId: access.profile.id, status: "ACTIVE" }, select: { gym: { select: { id: true, name: true } } }, orderBy: { gym: { name: "asc" } } }),
  ]);
  return <div className="trainer-page"><header className="trainer-page__heading trainer-page__heading--compact"><div><span>NUTRITION COACHING</span><h1>Nutrition plans</h1><p>Structure meals, portions, calories, and macros in immutable plan versions.</p></div><CreatePlan gyms={gyms.map((item) => item.gym)} kind="nutrition" /></header><section className="trainer-summary"><div><span>Active plans</span><strong>{plans.filter((plan) => plan.status === "ACTIVE").length}</strong></div><div><span>Drafts</span><strong>{plans.filter((plan) => plan.status === "DRAFT").length}</strong></div><div><span>Assignments</span><strong>{plans.reduce((sum, plan) => sum + plan._count.assignments, 0)}</strong></div><div><span>Templates</span><strong>{plans.filter((plan) => plan.isTemplate).length}</strong></div></section>{plans.length ? <div className="trainer-plan-grid trainer-plan-grid--nutrition">{plans.map((plan) => { const meals = plan.days.reduce((sum, day) => sum + day.meals.length, 0); const foods = plan.days.reduce((sum, day) => sum + day.meals.reduce((foodSum, meal) => foodSum + meal._count.foodItems, 0), 0); return <article key={plan.id}><div className="trainer-plan-card__top"><span><Icon name="heart" size={21} /></span><b className={`trainer-status trainer-status--${plan.status.toLowerCase()}`}>{plan.status}</b></div><small>{plan.isTemplate ? "TEMPLATE" : plan.gym?.name || "INDEPENDENT"} · VERSION {plan.version}</small><h2>{plan.title}</h2><p>{plan.description || "No description added."}</p><div className="trainer-plan-kcal">{plan.dailyCalories ? <><strong>{plan.dailyCalories.toLocaleString()}</strong><span>kcal / day</span></> : <span>Flexible calorie target</span>}</div><div className="trainer-plan-stats"><span><strong>{plan.days.length}</strong><small>days</small></span><span><strong>{meals}</strong><small>meals</small></span><span><strong>{foods}</strong><small>foods</small></span></div><PlanCardActions id={plan.id} kind="nutrition" status={plan.status} /></article>; })}</div> : <div className="trainer-panel trainer-empty"><Icon name="heart" size={26} /><strong>No nutrition plans yet</strong><span>Create a meal framework or reusable nutrition template.</span></div>}</div>;
}
