import { AvailabilityEditor, CreateSession, SessionActions } from "@/components/trainer/schedule-manager";
import { Icon } from "@/components/icon";
import { requireTrainerAccess } from "@/lib/trainer-access";
import { prisma } from "@/lib/prisma";

type PageProps = { searchParams: Promise<{ student?: string }> };
function day(value: Date) { return new Intl.DateTimeFormat("en", { weekday: "short", month: "short", day: "numeric" }).format(value); }
function time(value: Date) { return new Intl.DateTimeFormat("en", { hour: "numeric", minute: "2-digit" }).format(value); }

export default async function TrainerSchedulePage({ searchParams }: PageProps) {
  const access = await requireTrainerAccess(); const selected = (await searchParams).student; const now = new Date(); const from = new Date(now.getTime() - 14 * 86400000); const to = new Date(now.getTime() + 90 * 86400000);
  const [sessions, clients, gyms, slots] = await Promise.all([
    prisma.trainingSession.findMany({ where: { trainerId: access.profile.id, startsAt: { gte: from, lte: to } }, select: { id: true, title: true, startsAt: true, endsAt: true, status: true, notes: true, gym: { select: { name: true } }, trainerClient: { select: { user: { select: { name: true } } } } }, orderBy: { startsAt: "asc" } }),
    prisma.trainerClient.findMany({ where: { trainerId: access.profile.id, status: "ACTIVE" }, select: { id: true, user: { select: { name: true } } }, orderBy: { user: { name: "asc" } } }),
    prisma.gymTrainer.findMany({ where: { trainerId: access.profile.id, status: "ACTIVE" }, select: { gym: { select: { id: true, name: true } } }, orderBy: { gym: { name: "asc" } } }),
    prisma.trainerAvailability.findMany({ where: { trainerId: access.profile.id, isActive: true }, select: { dayOfWeek: true, startMinutes: true, endMinutes: true, timezone: true }, orderBy: [{ dayOfWeek: "asc" }, { startMinutes: "asc" }] }),
  ]);
  const upcoming = sessions.filter((session) => session.startsAt >= now && session.status === "SCHEDULED"); const history = sessions.filter((session) => session.startsAt < now || session.status !== "SCHEDULED").reverse().slice(0, 8);

  return <div className="trainer-page"><header className="trainer-page__heading trainer-page__heading--compact"><div><span>YOUR TIME</span><h1>Schedule</h1><p>Plan client sessions and publish your regular coaching hours.</p></div><CreateSession clients={clients.map((client) => ({ id: client.id, name: client.user.name }))} gyms={gyms.map((item) => item.gym)} selectedClient={selected} /></header><section className="trainer-summary"><div><span>Upcoming</span><strong>{upcoming.length}</strong></div><div><span>Completed recently</span><strong>{history.filter((item) => item.status === "COMPLETED").length}</strong></div><div><span>Weekly availability</span><strong>{slots.length} slots</strong></div></section><div className="trainer-schedule-layout"><section className="trainer-panel"><div className="trainer-panel__heading"><div><h2>Upcoming sessions</h2><p>The next 90 days</p></div><Icon name="calendar" size={18} /></div>{upcoming.length ? <div className="trainer-schedule-list">{upcoming.map((session) => <article key={session.id}><div className="trainer-schedule-time"><strong>{time(session.startsAt)}</strong><small>{day(session.startsAt)}</small></div><span className="trainer-schedule-line" /><div><strong>{session.title}</strong><small>{session.trainerClient.user.name} · {session.gym?.name || "Private / online"} · {Math.round((session.endsAt.getTime() - session.startsAt.getTime()) / 60000)} min</small>{session.notes && <p>{session.notes}</p>}</div><SessionActions id={session.id} status={session.status} /></article>)}</div> : <div className="trainer-empty"><Icon name="calendar" size={25} /><strong>No upcoming sessions</strong><span>Schedule a session with an active student.</span></div>}</section><AvailabilityEditor initialSlots={slots.map((slot) => ({ dayOfWeek: slot.dayOfWeek, startMinutes: slot.startMinutes, endMinutes: slot.endMinutes }))} timezone={slots[0]?.timezone || "Asia/Tehran"} /></div><section className="trainer-panel trainer-history"><div className="trainer-panel__heading"><div><h2>Recent session history</h2><p>Completed, cancelled, and missed sessions</p></div></div>{history.length ? <div>{history.map((session) => <article key={session.id}><span className={`trainer-status trainer-status--${session.status.toLowerCase()}`}>{session.status}</span><div><strong>{session.title}</strong><small>{session.trainerClient.user.name} · {day(session.startsAt)} at {time(session.startsAt)}</small></div><SessionActions id={session.id} status={session.status} /></article>)}</div> : <p className="trainer-availability-empty">No session history yet.</p>}</section></div>;
}
