import Link from "next/link";
import { notFound } from "next/navigation";
import { DemoCheckout } from "@/components/user/demo-checkout";
import { Icon } from "@/components/icon";
import { requireCurrentUser } from "@/lib/session";
import { prisma } from "@/lib/prisma";

type PageProps={params:Promise<{paymentId:string}>;searchParams:Promise<{token?:string}>};
function money(value:number,currency:string){try{return new Intl.NumberFormat("en",{style:"currency",currency,maximumFractionDigits:0}).format(value)}catch{return `${value.toLocaleString()} ${currency}`}}
export default async function CheckoutPage({params,searchParams}:PageProps){const user=await requireCurrentUser(["USER"]);const{paymentId}=await params;const{token=""}=await searchParams;const payment=await prisma.payment.findFirst({where:{id:paymentId,userId:user.id},select:{id:true,status:true,amount:true,currency:true,provider:true,type:true,plan:{select:{name:true,durationDays:true}},gym:{select:{name:true}},subscription:{select:{endDate:true}}}});if(!payment)notFound();return <div className="member-page checkout-page"><Link className="member-back" href="/user/subscriptions"><Icon name="chevron" size={14}/> Back to subscriptions</Link><section className="checkout-card"><header><span><Icon name="shield" size={24}/></span><div><small>SECURE CHECKOUT · {payment.provider.toUpperCase()}</small><h1>{payment.type==="RENEWAL"?"Renew subscription":"Activate membership"}</h1><p>Review your plan before completing payment.</p></div></header><div className="checkout-summary"><div><span>Gym</span><strong>{payment.gym.name}</strong></div><div><span>Plan</span><strong>{payment.plan.name}</strong></div><div><span>Duration</span><strong>{payment.plan.durationDays} days</strong></div><div><span>Amount</span><strong>{money(payment.amount,payment.currency)}</strong></div></div>{payment.status==="PENDING"||payment.status==="FAILED"?<><div className="demo-payment-banner"><Icon name="sparkles" size={18}/><p><strong>Demo payment provider</strong>This safe sandbox activates real application data without charging a card. Replace the provider adapter for production.</p></div><DemoCheckout paymentId={payment.id} token={token}/></>:<div className={`checkout-result checkout-result--${payment.status.toLowerCase()}`}><Icon name={payment.status==="SUCCEEDED"?"check":"clock"} size={20}/><strong>Payment {payment.status.toLowerCase()}</strong><Link href="/user/subscriptions">View subscriptions</Link></div>}</section></div>}
