import Link from "next/link";
import { notFound } from "next/navigation";
import { DemoCheckout } from "@/components/user/demo-checkout";
import { Icon } from "@/components/icon";
import { requireCurrentUser } from "@/lib/session";
import { prisma } from "@/lib/prisma";
import { faStatus } from "@/components/fa";

type PageProps={params:Promise<{paymentId:string}>;searchParams:Promise<{token?:string}>};
function money(value:number,currency:string){try{return new Intl.NumberFormat("fa-IR",{style:"currency",currency,maximumFractionDigits:0}).format(value)}catch{return `${value.toLocaleString("fa-IR")} ${currency}`}}
export default async function CheckoutPage({params,searchParams}:PageProps){const user=await requireCurrentUser(["USER"]);const{paymentId}=await params;const{token=""}=await searchParams;const payment=await prisma.payment.findFirst({where:{id:paymentId,userId:user.id},select:{id:true,status:true,amount:true,currency:true,provider:true,type:true,plan:{select:{name:true,durationDays:true}},gym:{select:{name:true}},subscription:{select:{endDate:true}}}});if(!payment)notFound();return <div className="member-page checkout-page"><Link className="member-back" href="/user/subscriptions"><Icon name="chevron" size={14}/> بازگشت به اشتراک‌ها</Link><section className="checkout-card"><header><span><Icon name="shield" size={24}/></span><div><small>پرداخت امن · {payment.provider.toUpperCase()}</small><h1>{payment.type==="RENEWAL"?"تمدید اشتراک":"فعال‌سازی عضویت"}</h1><p>پیش از تکمیل پرداخت، طرح‌تان را مرور کنید.</p></div></header><div className="checkout-summary"><div><span>باشگاه</span><strong>{payment.gym.name}</strong></div><div><span>طرح</span><strong>{payment.plan.name}</strong></div><div><span>مدت</span><strong>{payment.plan.durationDays} روز</strong></div><div><span>مبلغ</span><strong>{money(payment.amount,payment.currency)}</strong></div></div>{payment.status==="PENDING"||payment.status==="FAILED"?<><div className="demo-payment-banner"><Icon name="sparkles" size={18}/><p><strong>درگاه پرداخت نمایشی</strong>این محیط امن، بدون برداشت از کارت، داده واقعی برنامه را فعال می‌کند. برای محیط واقعی، آداپتور درگاه را جایگزین کنید.</p></div><DemoCheckout paymentId={payment.id} token={token}/></>:<div className={`checkout-result checkout-result--${payment.status.toLowerCase()}`}><Icon name={payment.status==="SUCCEEDED"?"check":"clock"} size={20}/><strong>پرداخت {faStatus(payment.status)}</strong><Link href="/user/subscriptions">مشاهده اشتراک‌ها</Link></div>}</section></div>}
