"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";

export function AssignmentPanel({ assignments, clients, kind, planId, published }: { assignments: Array<{ id: string; status: string; name: string; email: string; assignedAt: string }>; clients: Array<{ id: string; name: string }>; kind: "nutrition" | "workouts"; planId: string; published: boolean }) {
  const [pending, setPending] = useState(""); const [error, setError] = useState(""); const router = useRouter();
  async function assign(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending("assign"); setError(""); const form = new FormData(event.currentTarget); try { const response = await fetch(`/api/trainer/${kind}/${planId}/assignments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ trainerClientId: form.get("trainerClientId"), startDate: form.get("startDate") || null, endDate: form.get("endDate") || null }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Assignment failed."); return; } router.refresh(); } catch { setError("Unable to connect."); } finally { setPending(""); } }
  async function cancel(id: string) { setPending(id); const path = kind === "workouts" ? "workout-assignments" : "diet-assignments"; try { const response = await fetch(`/api/trainer/${path}/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "CANCELLED" }) }); if (response.ok) router.refresh(); } finally { setPending(""); } }
  return <section className="trainer-panel trainer-assignment-panel"><div className="trainer-panel__heading"><div><h2>Student assignments</h2><p>Publishing freezes this version for reliable history.</p></div></div>{published ? <form className="trainer-assign-form" onSubmit={assign}><select name="trainerClientId" required><option value="">Choose active student</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select><input name="startDate" type="date" /><input name="endDate" type="date" /><button className="trainer-primary-button" disabled={pending === "assign"}>{pending === "assign" ? "Assigning…" : "Assign plan"}</button></form> : <p className="trainer-plan-notice">Publish the plan before assigning it to a student.</p>}{error && <p className="trainer-form-error">{error}</p>}<div className="trainer-assignment-list">{assignments.map((assignment) => <article key={assignment.id}><span>{assignment.name.slice(0, 2).toUpperCase()}</span><div><strong>{assignment.name}</strong><small>{assignment.email} · {new Date(assignment.assignedAt).toLocaleDateString()}</small></div><b className={`trainer-status trainer-status--${assignment.status.toLowerCase()}`}>{assignment.status}</b>{assignment.status !== "CANCELLED" && <button disabled={pending === assignment.id} onClick={() => cancel(assignment.id)} type="button">Cancel</button>}</article>)}</div></section>;
}
