"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";

export function TrainerFeedbackForm({ clientId, nutritionLogs, workoutLogs }: { clientId: string; nutritionLogs: Array<{ id: string; label: string }>; workoutLogs: Array<{ id: string; label: string }> }) {
  const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const router = useRouter();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); setMessage(""); const form = new FormData(event.currentTarget); const context = String(form.get("context") || ""); const [kind, id] = context.split(":"); try { const response = await fetch("/api/trainer/feedback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ trainerClientId: clientId, type: form.get("type"), content: form.get("content"), workoutLogId: kind === "workout" ? id : null, nutritionLogId: kind === "nutrition" ? id : null }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "بازخورد ارسال نشد."); return; } event.currentTarget.reset(); setMessage("بازخورد ارسال و عضو مطلع شد."); router.refresh(); } catch { setError("اتصال برقرار نشد."); } finally { setPending(false); } }
  return <form className="trainer-feedback-form" onSubmit={submit}><div className="trainer-panel__heading"><div><h2>ارسال بازخورد</h2><p>راهنمایی را به یک ثبت مشخص یا پیشرفت کلی پیوند بزنید.</p></div></div><div><label><span>نوع</span><select name="type"><option value="GENERAL">عمومی</option><option value="WORKOUT">تمرین</option><option value="DIET">تغذیه</option><option value="PROGRESS">پیشرفت</option></select></label><label><span>زمینه</span><select name="context"><option value="">رابطه کلی مربی‌گری</option><optgroup label="ثبت‌های تمرین">{workoutLogs.map((log) => <option key={log.id} value={`workout:${log.id}`}>{log.label}</option>)}</optgroup><optgroup label="ثبت‌های تغذیه">{nutritionLogs.map((log) => <option key={log.id} value={`nutrition:${log.id}`}>{log.label}</option>)}</optgroup></select></label><label className="trainer-form-wide"><span>بازخورد</span><textarea name="content" placeholder="مشاهده‌ای شفاف و اقدام بعدی را بنویسید…" required rows={5} /></label></div>{(error || message) && <p className={error ? "trainer-form-error" : "trainer-form-success"}>{error || message}</p>}<footer><button className="trainer-primary-button" disabled={pending}>{pending ? "در حال ارسال…" : "ارسال بازخورد"}</button></footer></form>;
}
