"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";

export function TrainerFeedbackForm({ clientId, nutritionLogs, workoutLogs }: { clientId: string; nutritionLogs: Array<{ id: string; label: string }>; workoutLogs: Array<{ id: string; label: string }> }) {
  const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const router = useRouter();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); setMessage(""); const form = new FormData(event.currentTarget); const context = String(form.get("context") || ""); const [kind, id] = context.split(":"); try { const response = await fetch("/api/trainer/feedback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ trainerClientId: clientId, type: form.get("type"), content: form.get("content"), workoutLogId: kind === "workout" ? id : null, nutritionLogId: kind === "nutrition" ? id : null }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Unable to send feedback."); return; } event.currentTarget.reset(); setMessage("Feedback sent and member notified."); router.refresh(); } catch { setError("Unable to connect."); } finally { setPending(false); } }
  return <form className="trainer-feedback-form" onSubmit={submit}><div className="trainer-panel__heading"><div><h2>Send feedback</h2><p>Connect guidance to a specific log or overall progress.</p></div></div><div><label><span>Type</span><select name="type"><option value="GENERAL">General</option><option value="WORKOUT">Workout</option><option value="DIET">Nutrition</option><option value="PROGRESS">Progress</option></select></label><label><span>Context</span><select name="context"><option value="">Overall coaching relationship</option><optgroup label="Workout logs">{workoutLogs.map((log) => <option key={log.id} value={`workout:${log.id}`}>{log.label}</option>)}</optgroup><optgroup label="Nutrition logs">{nutritionLogs.map((log) => <option key={log.id} value={`nutrition:${log.id}`}>{log.label}</option>)}</optgroup></select></label><label className="trainer-form-wide"><span>Feedback</span><textarea name="content" placeholder="Share a clear observation and next action…" required rows={5} /></label></div>{(error || message) && <p className={error ? "trainer-form-error" : "trainer-form-success"}>{error || message}</p>}<footer><button className="trainer-primary-button" disabled={pending}>{pending ? "Sending…" : "Send feedback"}</button></footer></form>;
}
