"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/icon";

type PlanKind = "nutrition" | "workouts";

export function CreatePlan({ gyms, kind }: { gyms: Array<{ id: string; name: string }>; kind: PlanKind }) {
  const [open, setOpen] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const form = new FormData(event.currentTarget); const isWorkout = kind === "workouts"; const body = { title: form.get("title"), description: form.get("description"), gymId: form.get("gymId"), isTemplate: form.get("isTemplate") === "on", ...(isWorkout ? { days: [{ name: "Day 1", notes: null, exercises: [] }] } : { dailyCalories: form.get("dailyCalories"), dietaryRestrictions: form.get("dietaryRestrictions"), days: [{ name: "Day 1", notes: null, targetCalories: null, targetProtein: null, targetCarbs: null, targetFat: null, meals: [] }] }) }; try { const response = await fetch(`/api/trainer/${kind}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Unable to create plan."); return; } router.push(`/trainer/${kind}/${data.plan.id}`); router.refresh(); } catch { setError("Unable to connect."); } finally { setPending(false); } }
  if (!open) return <button className="trainer-primary-button" onClick={() => setOpen(true)}><Icon name="plus" size={16} /> New {kind === "workouts" ? "workout" : "nutrition"} plan</button>;
  return <form className="trainer-plan-create" onSubmit={submit}><div className="trainer-session-form__heading"><div><strong>Start a new {kind === "workouts" ? "workout" : "nutrition"} plan</strong><span>Create the foundation, then add structured details.</span></div><button onClick={() => setOpen(false)} type="button">×</button></div>{error && <p className="trainer-form-error">{error}</p>}<div className="trainer-form-grid"><label><span>Plan title</span><input autoFocus name="title" placeholder={kind === "workouts" ? "Foundation Strength" : "Balanced Performance"} required /></label><label><span>Gym context</span><select name="gymId"><option value="">Independent coaching</option>{gyms.map((gym) => <option key={gym.id} value={gym.id}>{gym.name}</option>)}</select></label>{kind === "nutrition" && <><label><span>Daily calorie target</span><input name="dailyCalories" min="0" type="number" /></label><label><span>Dietary restrictions</span><input name="dietaryRestrictions" placeholder="Allergies or preferences" /></label></>}<label className="trainer-form-wide"><span>Description</span><input name="description" placeholder="Goals and intended audience" /></label><label className="trainer-check"><input name="isTemplate" type="checkbox" /><span>Save as a reusable template</span></label></div><div className="trainer-form-actions"><button className="trainer-secondary-button" onClick={() => setOpen(false)} type="button">Cancel</button><button className="trainer-primary-button" disabled={pending}>{pending ? "Creating…" : "Create draft"}</button></div></form>;
}

export function PlanCardActions({ id, kind, status }: { id: string; kind: PlanKind; status: "DRAFT" | "ACTIVE" | "ARCHIVED" }) {
  const [pending, setPending] = useState(""); const [error, setError] = useState(""); const router = useRouter();
  async function statusUpdate(next: string) { setPending(next); setError(""); try { const response = await fetch(`/api/trainer/${kind}/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: next }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Update failed."); return; } router.refresh(); } catch { setError("Unable to connect."); } finally { setPending(""); } }
  async function clone(mode: "duplicate" | "version") { setPending(mode); setError(""); try { const response = await fetch(`/api/trainer/${kind}/${id}/clone`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Unable to copy plan."); return; } router.push(`/trainer/${kind}/${data.plan.id}`); router.refresh(); } catch { setError("Unable to connect."); } finally { setPending(""); } }
  return <div className="trainer-plan-actions"><button disabled={Boolean(pending)} onClick={() => router.push(`/trainer/${kind}/${id}`)}>{status === "DRAFT" ? "Edit" : "View"}</button>{status === "DRAFT" && <button className="publish" disabled={Boolean(pending)} onClick={() => statusUpdate("ACTIVE")}>{pending === "ACTIVE" ? "Publishing…" : "Publish"}</button>}{status === "ACTIVE" && <button disabled={Boolean(pending)} onClick={() => clone("version")}>{pending === "version" ? "Creating…" : "New version"}</button>}<button disabled={Boolean(pending)} onClick={() => clone("duplicate")}>{pending === "duplicate" ? "Copying…" : "Duplicate"}</button>{status !== "ARCHIVED" && <button disabled={Boolean(pending)} onClick={() => statusUpdate("ARCHIVED")}>Archive</button>}{error && <small>{error}</small>}</div>;
}
