"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/icon";

type PlanKind = "nutrition" | "workouts";

export function CreatePlan({ gyms, kind }: { gyms: Array<{ id: string; name: string }>; kind: PlanKind }) {
  const [open, setOpen] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const form = new FormData(event.currentTarget); const isWorkout = kind === "workouts"; const body = { title: form.get("title"), description: form.get("description"), gymId: form.get("gymId"), isTemplate: form.get("isTemplate") === "on", ...(isWorkout ? { days: [{ name: "روز ۱", notes: null, exercises: [] }] } : { dailyCalories: form.get("dailyCalories"), dietaryRestrictions: form.get("dietaryRestrictions"), days: [{ name: "روز ۱", notes: null, targetCalories: null, targetProtein: null, targetCarbs: null, targetFat: null, meals: [] }] }) }; try { const response = await fetch(`/api/trainer/${kind}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) { setError(data.error || "طرح ساخته نشد."); return; } router.push(`/trainer/${kind}/${data.plan.id}`); router.refresh(); } catch { setError("اتصال برقرار نشد."); } finally { setPending(false); } }
  if (!open) return <button className="trainer-primary-button" onClick={() => setOpen(true)}><Icon name="plus" size={16} /> طرح {kind === "workouts" ? "تمرینی" : "تغذیه"} تازه</button>;
  return <form className="trainer-plan-create" onSubmit={submit}><div className="trainer-session-form__heading"><div><strong>یک طرح {kind === "workouts" ? "تمرینی" : "تغذیه"} تازه شروع کنید</strong><span>اول پایه را بسازید، سپس جزئیات ساخت‌یافته بیفزایید.</span></div><button onClick={() => setOpen(false)} type="button">×</button></div>{error && <p className="trainer-form-error">{error}</p>}<div className="trainer-form-grid"><label><span>عنوان طرح</span><input autoFocus name="title" placeholder={kind === "workouts" ? "قدرت پایه" : "عملکرد متعادل"} required /></label><label><span>باشگاه</span><select name="gymId"><option value="">مربی‌گری مستقل</option>{gyms.map((gym) => <option key={gym.id} value={gym.id}>{gym.name}</option>)}</select></label>{kind === "nutrition" && <><label><span>هدف کالری روزانه</span><input name="dailyCalories" min="0" type="number" /></label><label><span>محدودیت‌های غذایی</span><input name="dietaryRestrictions" placeholder="حساسیت یا ترجیح غذایی" /></label></>}<label className="trainer-form-wide"><span>توضیحات</span><input name="description" placeholder="اهداف و مخاطبان" /></label><label className="trainer-check"><input name="isTemplate" type="checkbox" /><span>ذخیره به‌عنوان قالب آماده</span></label></div><div className="trainer-form-actions"><button className="trainer-secondary-button" onClick={() => setOpen(false)} type="button">انصراف</button><button className="trainer-primary-button" disabled={pending}>{pending ? "در حال ایجاد…" : "ایجاد پیش‌نویس"}</button></div></form>;
}

export function PlanCardActions({ id, kind, status }: { id: string; kind: PlanKind; status: "DRAFT" | "ACTIVE" | "ARCHIVED" }) {
  const [pending, setPending] = useState(""); const [error, setError] = useState(""); const router = useRouter();
  async function statusUpdate(next: string) { setPending(next); setError(""); try { const response = await fetch(`/api/trainer/${kind}/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: next }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "به‌روزرسانی انجام نشد."); return; } router.refresh(); } catch { setError("اتصال برقرار نشد."); } finally { setPending(""); } }
  async function clone(mode: "duplicate" | "version") { setPending(mode); setError(""); try { const response = await fetch(`/api/trainer/${kind}/${id}/clone`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "طرح کپی نشد."); return; } router.push(`/trainer/${kind}/${data.plan.id}`); router.refresh(); } catch { setError("اتصال برقرار نشد."); } finally { setPending(""); } }
  return <div className="trainer-plan-actions"><button disabled={Boolean(pending)} onClick={() => router.push(`/trainer/${kind}/${id}`)}>{status === "DRAFT" ? "ویرایش" : "مشاهده"}</button>{status === "DRAFT" && <button className="publish" disabled={Boolean(pending)} onClick={() => statusUpdate("ACTIVE")}>{pending === "ACTIVE" ? "در حال انتشار…" : "انتشار"}</button>}{status === "ACTIVE" && <button disabled={Boolean(pending)} onClick={() => clone("version")}>{pending === "version" ? "در حال ایجاد…" : "نسخه تازه"}</button>}<button disabled={Boolean(pending)} onClick={() => clone("duplicate")}>{pending === "duplicate" ? "در حال تکثیر…" : "تکثیر"}</button>{status !== "ARCHIVED" && <button disabled={Boolean(pending)} onClick={() => statusUpdate("ARCHIVED")}>بایگانی</button>}{error && <small>{error}</small>}</div>;
}
