"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/icon";

type Client = { id: string; name: string };
type Gym = { id: string; name: string };
type Slot = { dayOfWeek: number; endMinutes: number; startMinutes: number };

function timeValue(minutes: number) { return `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`; }
function toMinutes(value: string) { const [hours, minutes] = value.split(":").map(Number); return hours * 60 + minutes; }
const days = ["یکشنبه", "دوشنبه", "سه‌شنبه", "چهارشنبه", "پنجشنبه", "جمعه", "شنبه"];

export function CreateSession({ clients, gyms, selectedClient }: { clients: Client[]; gyms: Gym[]; selectedClient?: string }) {
  const [open, setOpen] = useState(Boolean(selectedClient)); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const form = new FormData(event.currentTarget); const startsAt = new Date(String(form.get("startsAt"))); const duration = Number(form.get("duration")); const endsAt = new Date(startsAt.getTime() + duration * 60000); try { const response = await fetch("/api/trainer/sessions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ trainerClientId: form.get("trainerClientId"), gymId: form.get("gymId"), title: form.get("title"), startsAt: startsAt.toISOString(), endsAt: endsAt.toISOString(), notes: form.get("notes") }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "جلسه زمان‌بندی نشد."); return; } setOpen(false); router.replace("/trainer/schedule"); router.refresh(); } catch { setError("اتصال برقرار نشد."); } finally { setPending(false); } }
  if (!open) return <button className="trainer-primary-button" onClick={() => setOpen(true)} type="button"><Icon name="plus" size={16} /> جلسه تازه</button>;
  return <form className="trainer-session-form" onSubmit={submit}><div className="trainer-session-form__heading"><div><strong>زمان‌بندی جلسه</strong><span>یک بلوک مربی‌گری متمرکز به تقویم‌تان اضافه کنید.</span></div><button onClick={() => setOpen(false)} type="button">×</button></div>{error && <p className="trainer-form-error">{error}</p>}<div className="trainer-form-grid trainer-form-grid--three"><label><span>شاگرد</span><select defaultValue={selectedClient || ""} name="trainerClientId" required><option value="">انتخاب شاگرد</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label><span>عنوان جلسه</span><input defaultValue="جلسه مربی‌گری" name="title" required /></label><label><span>باشگاه</span><select name="gymId"><option value="">خصوصی / آنلاین</option>{gyms.map((gym) => <option key={gym.id} value={gym.id}>{gym.name}</option>)}</select></label><label><span>زمان شروع</span><input name="startsAt" required type="datetime-local" /></label><label><span>مدت</span><select defaultValue="60" name="duration"><option value="30">۳۰ دقیقه</option><option value="45">۴۵ دقیقه</option><option value="60">۶۰ دقیقه</option><option value="90">۹۰ دقیقه</option><option value="120">۲ ساعت</option></select></label><label className="trainer-form-wide"><span>یادداشت‌های جلسه</span><input name="notes" placeholder="اهداف، آمادگی یا توضیح مکان" /></label></div><div className="trainer-form-actions"><button className="trainer-secondary-button" onClick={() => setOpen(false)} type="button">انصراف</button><button className="trainer-primary-button" disabled={pending}>{pending ? "در حال زمان‌بندی…" : "زمان‌بندی جلسه"}</button></div></form>;
}

export function SessionActions({ id, status }: { id: string; status: string }) {
  const [pending, setPending] = useState(""); const router = useRouter();
  async function update(next: string) { setPending(next); try { const response = await fetch(`/api/trainer/sessions/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: next }) }); if (response.ok) router.refresh(); } finally { setPending(""); } }
  return <div className="trainer-session-actions">{status === "SCHEDULED" && <><button className="complete" disabled={Boolean(pending)} onClick={() => update("COMPLETED")}>{pending === "COMPLETED" ? "در حال ذخیره…" : "تکمیل"}</button><button disabled={Boolean(pending)} onClick={() => update("NO_SHOW")}>عدم حضور</button><button disabled={Boolean(pending)} onClick={() => update("CANCELLED")}>انصراف</button></>}{status !== "SCHEDULED" && <button disabled={Boolean(pending)} onClick={() => update("SCHEDULED")}>جابه‌جایی</button>}</div>;
}

export function AvailabilityEditor({ initialSlots, timezone }: { initialSlots: Slot[]; timezone: string }) {
  const [slots, setSlots] = useState(initialSlots); const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const router = useRouter();
  function patch(index: number, values: Partial<Slot>) { setSlots((current) => current.map((slot, slotIndex) => slotIndex === index ? { ...slot, ...values } : slot)); }
  async function save() { setPending(true); setError(""); setMessage(""); try { const response = await fetch("/api/trainer/availability", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slots, timezone }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "دسترسی ذخیره نشد."); return; } setMessage("دسترسی هفتگی saved."); router.refresh(); } catch { setError("اتصال برقرار نشد."); } finally { setPending(false); } }
  return <section className="trainer-panel trainer-availability-editor"><div className="trainer-panel__heading"><div><h2>دسترسی هفتگی</h2><p>ساعت‌ها در {timezone} ذخیره می‌شوند.</p></div><button className="trainer-secondary-button" onClick={() => setSlots((current) => [...current, { dayOfWeek: 1, startMinutes: 540, endMinutes: 1020 }])} type="button"><Icon name="plus" size={14} /> افزودن بازه</button></div><div className="trainer-slot-list">{slots.map((slot, index) => <div key={`${index}-${slot.dayOfWeek}`}><select value={slot.dayOfWeek} onChange={(event) => patch(index, { dayOfWeek: Number(event.target.value) })}>{days.map((name, dayIndex) => <option key={name} value={dayIndex}>{name}</option>)}</select><input type="time" value={timeValue(slot.startMinutes)} onChange={(event) => patch(index, { startMinutes: toMinutes(event.target.value) })} /><span>تا</span><input type="time" value={timeValue(slot.endMinutes)} onChange={(event) => patch(index, { endMinutes: toMinutes(event.target.value) })} /><button aria-label="حذف بازه" onClick={() => setSlots((current) => current.filter((_, slotIndex) => slotIndex !== index))} type="button">×</button></div>)}</div>{!slots.length && <p className="trainer-availability-empty">هنوز بازه هفتگی اضافه نشده است؛ اعضا دسترسی منظم را نمی‌بینند.</p>}{(message || error) && <p className={error ? "trainer-form-error" : "trainer-form-success"}>{error || message}</p>}<div className="trainer-form-actions"><button className="trainer-primary-button" disabled={pending} onClick={save} type="button">{pending ? "در حال ذخیره…" : "ذخیره ساعات دسترسی"}</button></div></section>;
}
