"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/icon";

type Exercise = { key: string; name: string; sets: number | null; reps: string; weight: string; tempo: string; restSeconds: number | null; durationSeconds: number | null; distanceMeters: number | null; notes: string };
type Day = { key: string; name: string; notes: string; exercises: Exercise[] };
type Plan = { id: string; title: string; description: string | null; gymId: string | null; isTemplate: boolean; status: "DRAFT" | "ACTIVE" | "ARCHIVED"; version: number; assignmentCount: number; days: Day[] };
const blankExercise = (): Exercise => ({ key: crypto.randomUUID(), name: "", sets: 3, reps: "8–12", weight: "", tempo: "", restSeconds: 90, durationSeconds: null, distanceMeters: null, notes: "" });

export function WorkoutPlanEditor({ gyms, plan }: { gyms: Array<{ id: string; name: string }>; plan: Plan }) {
  const [title, setTitle] = useState(plan.title); const [description, setDescription] = useState(plan.description || ""); const [gymId, setGymId] = useState(plan.gymId || ""); const [isTemplate, setTemplate] = useState(plan.isTemplate); const [days, setDays] = useState(plan.days); const [pending, setPending] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const router = useRouter(); const editable = plan.status === "DRAFT" && plan.assignmentCount === 0;
  function patchDay(index: number, values: Partial<Day>) { setDays((items) => items.map((day, i) => i === index ? { ...day, ...values } : day)); }
  function patchExercise(dayIndex: number, exerciseIndex: number, values: Partial<Exercise>) { setDays((items) => items.map((day, i) => i === dayIndex ? { ...day, exercises: day.exercises.map((exercise, j) => j === exerciseIndex ? { ...exercise, ...values } : exercise) } : day)); }
  async function save() { setPending("save"); setError(""); setMessage(""); try { const response = await fetch(`/api/trainer/workouts/${plan.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, description, gymId, isTemplate, days: days.map((day) => ({ name: day.name, notes: day.notes, exercises: day.exercises.map((exercise) => ({ name: exercise.name, sets: exercise.sets, reps: exercise.reps, weight: exercise.weight, tempo: exercise.tempo, restSeconds: exercise.restSeconds, durationSeconds: exercise.durationSeconds, distanceMeters: exercise.distanceMeters, notes: exercise.notes })) })) }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Unable to save plan."); return; } setMessage("Workout plan saved."); router.refresh(); } catch { setError("Unable to connect."); } finally { setPending(""); } }
  async function publish() { if (editable) { await save(); } setPending("publish"); setError(""); try { const response = await fetch(`/api/trainer/workouts/${plan.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "ACTIVE" }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Unable to publish plan."); return; } router.refresh(); } finally { setPending(""); } }
  return <section className="trainer-plan-editor"><div className="trainer-plan-editor__meta"><div><label><span>Plan title</span><input disabled={!editable} value={title} onChange={(event) => setTitle(event.target.value)} /></label><label><span>Gym context</span><select disabled={!editable} value={gymId} onChange={(event) => setGymId(event.target.value)}><option value="">Independent coaching</option>{gyms.map((gym) => <option key={gym.id} value={gym.id}>{gym.name}</option>)}</select></label><label className="trainer-form-wide"><span>Description</span><textarea disabled={!editable} rows={3} value={description} onChange={(event) => setDescription(event.target.value)} /></label><label className="trainer-check"><input checked={isTemplate} disabled={!editable} type="checkbox" onChange={(event) => setTemplate(event.target.checked)} /><span>Reusable template</span></label></div><aside><span className={`trainer-status trainer-status--${plan.status.toLowerCase()}`}>{plan.status}</span><strong>Version {plan.version}</strong><small>{plan.assignmentCount} assignments</small></aside></div>{!editable && <p className="trainer-plan-notice"><Icon name="lock" size={15} /> Published or assigned versions are read-only. Create a new version to make changes.</p>}
    <div className="trainer-workout-days">{days.map((day, dayIndex) => <article className="trainer-workout-day" key={day.key}><header><span>{dayIndex + 1}</span><input disabled={!editable} value={day.name} onChange={(event) => patchDay(dayIndex, { name: event.target.value })} placeholder="Training day name" /><input disabled={!editable} value={day.notes} onChange={(event) => patchDay(dayIndex, { notes: event.target.value })} placeholder="Day notes" />{editable && <button aria-label="Remove day" onClick={() => setDays((items) => items.filter((_, i) => i !== dayIndex))}>×</button>}</header><div className="trainer-exercise-head"><span>Exercise</span><span>Sets</span><span>Reps</span><span>Weight</span><span>Tempo</span><span>Rest</span><span /></div>{day.exercises.map((exercise, exerciseIndex) => <div className="trainer-exercise-row" key={exercise.key}><input disabled={!editable} value={exercise.name} onChange={(event) => patchExercise(dayIndex, exerciseIndex, { name: event.target.value })} placeholder="Exercise name" /><input disabled={!editable} min="1" type="number" value={exercise.sets ?? ""} onChange={(event) => patchExercise(dayIndex, exerciseIndex, { sets: event.target.value ? Number(event.target.value) : null })} /><input disabled={!editable} value={exercise.reps} onChange={(event) => patchExercise(dayIndex, exerciseIndex, { reps: event.target.value })} /><input disabled={!editable} value={exercise.weight} onChange={(event) => patchExercise(dayIndex, exerciseIndex, { weight: event.target.value })} placeholder="RPE / kg" /><input disabled={!editable} value={exercise.tempo} onChange={(event) => patchExercise(dayIndex, exerciseIndex, { tempo: event.target.value })} placeholder="3-1-1" /><input disabled={!editable} min="0" type="number" value={exercise.restSeconds ?? ""} onChange={(event) => patchExercise(dayIndex, exerciseIndex, { restSeconds: event.target.value ? Number(event.target.value) : null })} />{editable && <button aria-label="Remove exercise" onClick={() => patchDay(dayIndex, { exercises: day.exercises.filter((_, i) => i !== exerciseIndex) })}>×</button>}</div>)}{editable && <button className="trainer-add-row" onClick={() => patchDay(dayIndex, { exercises: [...day.exercises, blankExercise()] })}><Icon name="plus" size={14} /> Add exercise</button>}</article>)}{editable && <button className="trainer-add-day" onClick={() => setDays((items) => [...items, { key: crypto.randomUUID(), name: `Day ${items.length + 1}`, notes: "", exercises: [blankExercise()] }])}><Icon name="plus" size={15} /> Add training day</button>}</div>
    {(error || message) && <p className={error ? "trainer-form-error" : "trainer-form-success"}>{error || message}</p>}<div className="trainer-plan-editor__actions">{editable && <button className="trainer-secondary-button" disabled={Boolean(pending)} onClick={save}>{pending === "save" ? "Saving…" : "Save draft"}</button>}{plan.status === "DRAFT" && <button className="trainer-primary-button" disabled={Boolean(pending)} onClick={publish}>{pending === "publish" ? "Publishing…" : "Publish version"}</button>}</div></section>;
}
